# Generated by Django 3.1.1 on 2020-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_time_to_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
