# Generated by Django 3.1.1 on 2020-09-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time_to_finish',
            field=models.IntegerField(default=0),
        ),
    ]
