# Generated by Django 3.1.1 on 2020-09-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationUser', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
