# Generated by Django 3.1.1 on 2020-09-13 19:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_step_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
