# Generated by Django 3.1.1 on 2020-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200913_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
