# Generated by Django 3.1.1 on 2020-09-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_learningobjective_teacher'),
        ('lessons', '0005_auto_20200913_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
