# Generated by Django 3.1.1 on 2020-09-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
