# Generated by Django 3.1.1 on 2020-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_assignment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='lesson_materials',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='step',
            name='teacher_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
